### ISSUE TITLE
Arduino for windows 

### ISSUE THREAD

**Issue by bakchos1** [docdawning/Illuminatrix#1]
Hello, thanks for the code,

is there a way to compile and upload using windows PC to test on my arduino Uno ?

**Comment by docdawning** [comment]
Sorry I didn't see your message sooner. You can absolutely do this. Compile the sketch and upload to your arduino normally. Wire-up your LEDs or transistors driving them directly to the pins used in the firmware code. You'll then need to know how to use the command set to manually command the firmware to do things over the serial console.
