### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by valiobg** [docdawning/Illuminatrix#3]
I uploaded the code with Arduino IDE to arduino uno. I installed the plugin to my RPI3. Then I entered the correct port in plugin settings in Octoprint but the plugin doesn't work. I need help !

**Comment by docdawning** [comment]
It could be a permissions issue, perhaps. I suggest trying to command the firmware directly from your Pi's command line, as the user that runs Octoprint.

**Comment by docdawning** [comment]
@valiobg I'm closing this. If you still need help let me know.
