### ISSUE TITLE
Unsure how to setup port

### ISSUE THREAD

**Issue by andrewvanlagen** [docdawning/Illuminatrix#4]
How do u set up the port and make it work

**Comment by docdawning** [comment]
Is the Arduino firmware flashed on to your Arduino?

**Comment by andrewvanlagen** [comment]
Yes

**Comment by docdawning** [comment]
When you attach to the Arduino to your device running OctoPrint, what port does the Arduino appear on?

**Comment by andrewvanlagen** [comment]
Arduino on 9600 and octoprint on 152000

**Comment by docdawning** [comment]
Those are baud rates. 

Ports will be something like `/dev/ttyACM0` or `/dev/ttyUSB0`

Try this (it assumes you're not using a direct RS-232 connection):

1. Power up the computer running Octoprint
2. Unplug the Arduino, if it's already plugged in, else skip this step
3. Open a terminal/ssh session to your computer. Run the command `dmesg`. Just pay rough attention to how the end of the output looks, don't look too carefully.
4. Plugin the Arduino and re-run `dmesg`. Note the output should now end differently. One of the last few lines should contain the name of the port that the Arduino is connected to. I would guess it'd be `/dev/ttyUSB0` or `/dev/ttyUSB1`
5. Open the Illuminatrix settings in Octoprint, enter the port name you saw in the last step and set the baud rate to 9600.

Give that a whirl and see how you do.

**Comment by docdawning** [comment]
@andrewvanlagen Did you get it working?
